version: '3.9'

services:
  db:
    image: mysql:5.7
    container_name: newsletter_db
    restart: always
    environment:
      MYSQL_DATABASE: 'newsletter'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'senha'
      MYSQL_RANDOM_ROOT_PASSWORD: true
    volumes:
      - ./db/:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "admin", "-psenha" ]
      start_period: 5s
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - backend

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: newsletter_backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080
    networks:
      - backend


networks:
  backend:

  frontend:
